baseurl = "/"
languageCode = "en-us"
title = "Daily R"
theme = "hugo-xmag"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[gitment]
  enable = true
  owner = 'yufree'
  repo = 'daily'
  client_id = 'e85e26891e27a971c2a8' # Client ID
  client_secret = '75394d3d25dbc264a72ef96244bee2c5ca7042db' # Client secret

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "light news/blog aggregator website for R"
    summary_length = 300
    github_edit = "https://github.com/yufree/daily/edit/master/content/"
    footer = "&copy; [Miao YU](https://yufree.cn) 2018 | [Github](https://github.com/yufree) | [Twitter](https://twitter.com/yu_free)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
